" generated by Puppet module vim

:set bg=dark
if has('gui_running')
	set background=light
else
	set background=dark
endif
filetype plugin indent on
highlight comment ctermfg=darkgray
set splitbelow
set splitright
set fileformat=unix
set encoding=utf-8
set expandtab
set number
set pastetoggle=<F6>
set shiftwidth=2
set softtabstop=2
set tabstop=2
silent! colorscheme solarized
syntax on
if filereadable(glob("~/.vimrc.local"))
	source ~/.vimrc.local
endif
execute pathogen#infect()
call pathogen#helptags()
